<%@ Page Title="Veg Store" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="Veg_Store.aspx.cs" Inherits="Veg_Store" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            margin-top: 0px;
        }
        body{
            margin-top:170px;
        }

    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


    <center>  <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CssClass="auto-style1" DataKeyNames="itemid" DataSourceID="SqlDataSource2" Height="165px" ShowFooter="True" Width="682px" Font-Bold="True" Font-Size="Medium" GridLines="None" AllowPaging="True" AllowSorting="True" CellPadding="4" ForeColor="#333333">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:TemplateField HeaderText="ItemPics">
                <ItemTemplate>
                    <asp:Image ID="Image2" runat="server" Height="150px" ImageUrl='<%# Eval("image") %>' Width="150px" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="offer" HeaderText="Offer" SortExpression="offer" />
            <asp:BoundField DataField="itemid" HeaderText="Item Id" ReadOnly="True" SortExpression="itemid" />
            <asp:BoundField DataField="iname" HeaderText="Name" SortExpression="item_name" />
            <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
            <asp:BoundField DataField="ppu" HeaderText="Per_Unit" SortExpression="price_per_Unit" />
            <asp:BoundField DataField="stockQuantity" HeaderText="Total_Quantity" SortExpression="item_quantity" />
            <asp:BoundField DataField="stockUnit" HeaderText="Total_Unit" SortExpression="item_unit" />
            <asp:BoundField DataField="category" HeaderText="Category" SortExpression="category" />
            <asp:BoundField DataField="stockStatus" HeaderText="Stock Status" SortExpression="stockstatus" />
            <asp:BoundField DataField="description" HeaderText="item_dscrp" SortExpression="item_dscrp" />
            <asp:BoundField DataField="image" HeaderText="Image Link" SortExpression="item_img" />
        </Columns>
        <EditRowStyle BorderStyle="None" BackColor="#7C6F57" />
        <FooterStyle BackColor="Yellow" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="Yellow" BorderWidth="1px" Font-Bold="True" Font-Size="Large" ForeColor="Red" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#E3EAEB" />
        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F8FAFA" />
        <SortedAscendingHeaderStyle BackColor="#246B61" />
        <SortedDescendingCellStyle BackColor="#D4DFE1" />
        <SortedDescendingHeaderStyle BackColor="#15524A" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:DbCon %>" DeleteCommand="DELETE FROM [tblItem] WHERE [itemid] = @original_itemid" InsertCommand="INSERT INTO [tblItem] ([iname], [price], [ppu], [stockQuantity], [stockUnit], [category], [image], [stockStatus], [description], [offer]) VALUES (@iname, @price, @ppu, @stockQuantity, @stockUnit, @category, @image, @stockStatus, @description, @offer)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [tblItem] WHERE ([category] = @category)" UpdateCommand="UPDATE [tblItem] SET [iname] = @iname, [price] = @price, [ppu] = @ppu, [stockQuantity] = @stockQuantity, [stockUnit] = @stockUnit, [category] = @category, [image] = @image, [stockStatus] = @stockStatus, [description] = @description, [offer] = @offer WHERE [itemid] = @original_itemid">
        <DeleteParameters>
            <asp:Parameter Name="original_itemid" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="iname" Type="String" />
            <asp:Parameter Name="price" Type="Int32" />
            <asp:Parameter Name="ppu" Type="String" />
            <asp:Parameter Name="stockQuantity" Type="Int32" />
            <asp:Parameter Name="stockUnit" Type="String" />
            <asp:Parameter Name="category" Type="String" />
            <asp:Parameter Name="image" Type="String" />
            <asp:Parameter Name="stockStatus" Type="String" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter Name="offer" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:Parameter DefaultValue="Veg" Name="category" Type="String" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="iname" Type="String" />
            <asp:Parameter Name="price" Type="Int32" />
            <asp:Parameter Name="ppu" Type="String" />
            <asp:Parameter Name="stockQuantity" Type="Int32" />
            <asp:Parameter Name="stockUnit" Type="String" />
            <asp:Parameter Name="category" Type="String" />
            <asp:Parameter Name="image" Type="String" />
            <asp:Parameter Name="stockStatus" Type="String" />
            <asp:Parameter Name="description" Type="String" />
            <asp:Parameter Name="offer" Type="String" />
            <asp:Parameter Name="original_itemid" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource></center> 


</asp:Content>

